export const loginApi = `auth/login`;
export const signupApi = `auth/signup`;
export const forgotpassword = `auth/forgot_password`;
export const serviceApi = `services`;
export const productApi = `products`;
export const productFilterApi = `products/filterProduct`;
export const customerApi = `customers/addCustomer`;
export const customerDetailsApi = `customers/customerWithInvoices`;
export const updatecustomerApi = `customers/updateCustomer`;
export const listcustomerApi = `customers/listCustomers`;
export const deletecustomerApi = `customers/deleteCustomer`;
export const filterCustomerApi = `customers/filterCustomer`;
export const filterVendorApi = `vendor/filterByvendorName`;
export const activateCustomerApi = `customers/activateCustomer`;
export const deactivateCustomerApi = `customers/deactivateCustomer`;
export const vendorApi = `vendor`;
export const invoiceApi = `invoice`;
export const userDetailsApi = `/users/profile`;
export const currencyApi = "currency?country=ind";
// export const unitsApi = "units/unitList";
export const unitsApi = "units/unitList";
export const addUnitsApi = "units";
export const viewUnitsApi = "units/viewUnit";
export const deleteUnitsApi = "units/delete";
export const unitsFilterApi = "/units/filterUnits";
export const staffApi = "staff/staffList";
export const addStaffApi = "staff";
export const viewStaffApi = "staff/viewStaff";
export const deleteStaffApi = "staff/delete";
export const staffFilterApi = "/staff/filterStaff";
export const taxListApi = "tax";
export const estimatetApi = "estimates";
export const itemListApi = "invoice/prodcutorservice";
export const categoryApi = "category";
export const categoryFilterApi = "category/filterByCategoryName";
export const addLedger = "ledger/addData";
export const getLedger = "ledger/getAllData";
export const viewLedger = "ledger/getById";
export const updateLedger = "ledger";
export const deletedLedger = "ledger";
export const addVendor = "vendor/addVendor";
export const listVendor = "vendor/listVendor";
export const deleteVendor = "vendor/deleteVendor";
export const updateVendor = "vendor/updateVendor";
export const viewVendor = "vendor/viewVendor";
export const viewCustomerApi = "customers/viewCustomer";
// Purchases
export const addPurchaseApi = "purchases/addPurchase";
export const listPurchasesApi = "purchases/listPurchases";
export const updatePurchaseApi = "purchases/updatePurchase";
export const viewPurchaseApi = "purchases/viewPurchase";
export const deletePurchaseApi = "purchases/deletePurchase";
export const filterPurchasesApi = "purchases/filterPurchases";

export const addCreditNote = "/credit_note/addCreditNote";

// Inventory
export const listInventory = "inventory/inventoryList";
export const deleteInventory = "/inventory/deleteInventory";
export const addStockInventory = "/inventory/addStock";
export const outStockInventory = "/inventory/removeStock";
export const filterInventory = "/inventory/filter";

export const debitFilter = "debit_note/filterByVendor";
