export const editorConfig = {
  toolbar: {
    items: [
      "heading",
      "|",
      "bold",
      "italic",
      // "underline",
      // "strikethrough",
      "|",
      "link",
      "bulletedList",
      "numberedList",
      "|",
      "outdent",
      "indent",
      "|",
      // "blockQuote",
      // "insertTable",
      "|",
      "undo",
      "redo",
    ],
    plugins: [
      "Heading",
      "Bold",
      "Italic",
      // "Underline",
      // "Strikethrough",
      "Link",
      "List",
      "Indent",
      "Table",
      "Undo",
      "Redo",
    ],
    indentBlock: {
      offset: 20,
      unit: "px",
    },
  },
};
