import {
  img15,
  img19,
  img2,
  img3,
  img4,
  img5,
  img6,
  img7,
} from "../../common/imagepath";

export default {
  Data: [
    {
      id: 1,
      Invoice: "#4987",
      Category: "Food",
      Created: "23 Mar 2023",
      Name: "John Smith",
      img: img15,
      Email: "john@example.com",
      Total: "$1,54,220",
      Paid: "$1,50,000",
      Payment: "Cash",
      Balance: "$2,54,00",
      Due: "25 Mar 2023",
      Status: "Pending",
      Action: "",
    },
    {
      id: 6,
      Invoice: "#4992",
      Category: "Stationary",
      Created: "16 Nov 2022",
      Name: "Randall",
      img: img19,
      Email: "randall@example.com",
      Total: "$5,54,220",
      Paid: "$6,50,000",
      Payment: "Cash",
      Balance: "$4,220",
      Due: "25 Feb 2023",
      Status: "Pending",
      Action: "",
    },
  ],
};
